server:
  port: 8070

rapid:
  api:
    host_hotel: hotels4.p.rapidapi.com
    host_covid: covid-19-data.p.rapidapi.com
    key: 77d2ce92ecmshd2205d0a1a8a70cp1ddf14jsnb92ce02c4392

ftp:
  server:
    protocol: ftp
    username: user
    password: user
    host: localhost
    port: 21
    remote-directory: remoteDirectory
    passive-mode: true

camel:
  springboot:
    main-run-controller: true